rule MALPEDIA_Win_Virlock_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "a53ad870-36e8-5483-a3c7-250260a5d06b"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.virlock"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.virlock_auto.yar#L1-L131"
		license_url = "N/A"
		logic_hash = "2251c81b77f733b642183ccf22ad3a25fb0df2e83278219ff44fcff0baf92b0d"
		score = 75
		quality = 69
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { e8???????? e8???????? ff15???????? 61 3bcb 7532 60 }
		$sequence_1 = { 9d cde6 81b4e570805c4af32b0cf0 e602 a4 b592 9c }
		$sequence_2 = { 68???????? eb0a 68???????? 68???????? e8???????? 83fa00 751b }
		$sequence_3 = { 81f2???????? 81f35e473bfc 81f308f661fc 81f37dc97000 e8???????? bb8aedf4f9 baf2edecff }
		$sequence_4 = { 45 58 58 46 54 4f 53 }
		$sequence_5 = { eb07 3106 83c604 ebea 83f901 754a }
		$sequence_6 = { 42 4b 4e 53 47 4b 56 }
		$sequence_7 = { 44 56 53 49 4f 45 }
		$sequence_8 = { 8bf8 90 e9???????? 8807 90 42 90 }
		$sequence_9 = { bb53203dfd 3106 83c604 bb975ea4f7 ebb5 83f901 }

	condition:
		7 of them and filesize <4202496
}
