rule MALPEDIA_Win_Qtbot_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "ec8aa97a-290d-593c-aa5f-6c160f3c38cf"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.qtbot"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.qtbot_auto.yar#L1-L168"
		license_url = "N/A"
		logic_hash = "2c7689c956559567f13a9ec6cae95c5c067935d56f8491bff1983eb40f5f2838"
		score = 60
		quality = 25
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 89450c 8d4301 0fb6d8 8a941dfcfeffff 0fb6c2 }
		$sequence_1 = { 75e9 5b 5d c20400 }
		$sequence_2 = { 25ffffff00 42 8a1a 84db }
		$sequence_3 = { 8b049a 03c6 50 e8???????? }
		$sequence_4 = { 33c0 53 8a1a 6bc80d 0fb6c3 83c0d0 }
		$sequence_5 = { 03d6 8b481c 8b4018 03ce }
		$sequence_6 = { 40 89450c 83ef01 75b1 8b4510 5f 5e }
		$sequence_7 = { 85ff 7455 8b4510 89450c }
		$sequence_8 = { 894dfc eb0e 8b14957c300010 49 0fafd1 0155fc }
		$sequence_9 = { 8bd8 8d7e08 7504 8b2f eb02 }
		$sequence_10 = { 0fb6805a210010 ff2485f6200010 8b8614080000 3b45f4 7e03 8945f4 8365fc00 }
		$sequence_11 = { 6a00 ff15???????? 833e05 7521 6a10 6a40 ff15???????? }
		$sequence_12 = { 8db720080000 833e00 751e 837efcff 7518 8b46f8 8b04855c300010 }
		$sequence_13 = { 8b46f8 834de4ff 49 c745e8ff000000 8b3c857c300010 }
		$sequence_14 = { 33c0 8b7df4 8b0c855c300010 c1e705 33d2 03fe }
		$sequence_15 = { e8???????? 59 837e04ff 8bd8 8d7e08 }

	condition:
		7 of them and filesize <57344
}
