rule MALPEDIA_Win_Rdat_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "92191fa2-5f3d-5b42-a025-816ea5c7ba9a"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rdat"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.rdat_auto.yar#L1-L164"
		license_url = "N/A"
		logic_hash = "258a7b0e2fbdc995f078ce1c969b2a27e77e31fae7722d9e4f1fdbfa2416146c"
		score = 60
		quality = 45
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 3b7744 0f8c19ffffff 8b87ac020000 33ed }
		$sequence_1 = { 48ffc3 4038341a 75f7 4883791810 488b7910 7203 488b09 }
		$sequence_2 = { 4863ed 4885ed 0f8ed8000000 8b54b430 }
		$sequence_3 = { 4c8bc3 4c0f42c7 4d85c0 7504 8bc6 }
		$sequence_4 = { 4889442470 448bb910010000 4532e4 448aea 488bd9 4585ff 0f8e1e020000 }
		$sequence_5 = { 4533ff 4c8bf1 44397944 0f8e64010000 }
		$sequence_6 = { 48894108 4c8b05???????? 488b15???????? 89442420 4d85c0 }
		$sequence_7 = { 488b09 483bfb 4c8bc3 4c0f42c7 }
		$sequence_8 = { 45380401 75f7 4c8bc0 498bd1 488d4c2438 }
		$sequence_9 = { e8???????? 4898 4885c0 751e 483bfb 7313 83c8ff }
		$sequence_10 = { 85c0 740b b9e8030000 ff15???????? }
		$sequence_11 = { 4863f0 33d2 8bc2 48c1e006 }
		$sequence_12 = { 3b566c 0f8d9e000000 488b4660 3b5668 7c1d 2b5668 }
		$sequence_13 = { 7203 488b00 4c8bc0 498bd7 488d4de0 }
		$sequence_14 = { 0f84f5000000 4883f910 7205 488b07 }
		$sequence_15 = { 488d8c2490060000 e8???????? 90 488b942490060000 803a00 7505 4d8bc6 }

	condition:
		7 of them and filesize <1573888
}
