rule MALPEDIA_Win_Strongpity_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "74f27818-19f0-5cf0-92fb-64e00785ec08"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.strongpity"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.strongpity_auto.yar#L1-L169"
		license_url = "N/A"
		logic_hash = "61a3d3556929a6d92379ea8e74c4d3e507b020fc18a8d58904a2026c1434bfed"
		score = 60
		quality = 45
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 50 33c0 d1f9 50 51 53 }
		$sequence_1 = { 75f8 ff75d0 68???????? ff36 e8???????? }
		$sequence_2 = { 41 83ea01 75f7 50 e8???????? 59 }
		$sequence_3 = { e8???????? 8b4608 83c418 6a2f 59 }
		$sequence_4 = { 8945f8 f7d8 56 57 }
		$sequence_5 = { 33db c745f804000000 53 ff7710 895df4 ff770c }
		$sequence_6 = { ba???????? f3a5 8bf2 668b02 83c202 }
		$sequence_7 = { 83e801 7408 6a02 58 884612 }
		$sequence_8 = { 0107 83be8800000002 8b07 0f85ad000000 83f814 }
		$sequence_9 = { 012e 885c240a e9???????? 84db 0f8434020000 }
		$sequence_10 = { 5f 8d4503 5d 5b 8b4c2428 }
		$sequence_11 = { 7417 48 7545 39812c020000 7433 8b8124020000 }
		$sequence_12 = { 5f 8b4c2408 5e 5b }
		$sequence_13 = { 5f 8d4502 5d 5e 5b 8b4c2468 }
		$sequence_14 = { 012e 885c240a ebc3 80fb5d 7520 837c240c00 0f85fe020000 }
		$sequence_15 = { 5f 8bc3 5b c3 8d4638 50 e8???????? }

	condition:
		7 of them and filesize <999424
}
