rule MALPEDIA_Win_Synccrypt_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "06111ba7-b1d3-5613-b1dc-5c5b2d1d9432"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.synccrypt"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.synccrypt_auto.yar#L1-L134"
		license_url = "N/A"
		logic_hash = "f349f89fd6eccd96b82f1ed169c1d5231d52d67328e2977c4a89bd9cc0fef158"
		score = 75
		quality = 45
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { c744240477000000 c7042422000000 e8???????? e9???????? c7442410af000000 c744240c94195900 c74424087a000000 }
		$sequence_1 = { ba01000000 89f8 e8???????? 85c0 8b4c242c 0f84aa000000 8b4714 }
		$sequence_2 = { 892c24 e8???????? 892c24 89c7 e8???????? 85c0 7517 }
		$sequence_3 = { c1e806 85c0 7523 897358 83c318 89742408 891c24 }
		$sequence_4 = { e8???????? 85c0 74c8 8d442414 8974240c 895c2408 89442404 }
		$sequence_5 = { e8???????? 85c0 0f8413010000 8d7804 89c1 c7406800000000 89c3 }
		$sequence_6 = { f6400c01 7451 891c24 e8???????? 83c001 c744240897010000 c7442404???????? }
		$sequence_7 = { c7442404???????? c7042402000000 a3???????? e8???????? c7442404???????? c704240b000000 a3???????? }
		$sequence_8 = { e8???????? 893424 e8???????? 8b442430 890424 e8???????? 39c7 }
		$sequence_9 = { 890424 8954240c e8???????? 3b6c2418 8d45fe 746e 8b570c }

	condition:
		7 of them and filesize <4489216
}
