rule MALPEDIA_Win_Aresloader_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "aecf8195-bc3f-5d42-bd81-bfa1c242c64d"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.aresloader"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.aresloader_auto.yar#L1-L109"
		license_url = "N/A"
		logic_hash = "3fed3bf2cf5088e9a8f4396999f890e21fa81afee0e4b5adddfaf27ad4b3888c"
		score = 60
		quality = 25
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 85db 7435 85f6 7431 }
		$sequence_1 = { c744241410000000 c744241000000000 c744240c00000000 c744240800000000 c744240400000000 }
		$sequence_2 = { 8b6c243c 3d???????? 741d 896c243c }
		$sequence_3 = { a1???????? 8b5c2430 8b742434 8b7c2438 8b6c243c 3d???????? }
		$sequence_4 = { 8b7c2438 8b6c243c 85db 7435 }
		$sequence_5 = { 7431 896c240c 897c2408 895c2404 893424 }
		$sequence_6 = { 8b6c243c 85db 7435 85f6 }
		$sequence_7 = { 8b7c2438 8b6c243c 3d???????? 741d 896c243c }
		$sequence_8 = { 893424 e8???????? 85c0 7831 }
		$sequence_9 = { 7431 896c240c 897c2408 895c2404 }

	condition:
		7 of them and filesize <2657280
}
