rule MALPEDIA_Elf_Blackcat_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "8a7e13ba-9ed1-59ed-8fb9-9aaa610fbd94"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/elf.blackcat"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/elf.blackcat_auto.yar#L1-L113"
		license_url = "N/A"
		logic_hash = "1ac97428ed273512eef4209d87a29f49ce26e88d11cb15b15e2f2687ea017381"
		score = 60
		quality = 45
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { e8???????? 0f0b 90 90 90 90 53 }
		$sequence_1 = { 69c0???????? c1e811 6bf064 29f2 0fb7d2 }
		$sequence_2 = { e8???????? 0f0b 90 53 }
		$sequence_3 = { 89c1 3d???????? 7319 c1e906 }
		$sequence_4 = { 660f7f8424f0010000 660f7f8424e0010000 660f7f8424d0010000 660f7f8424c0010000 660f7f8424b0010000 }
		$sequence_5 = { d1e9 01d1 c1e902 8d14cd00000000 }
		$sequence_6 = { b801000000 81f9???????? 0f823fffffff b802000000 }
		$sequence_7 = { 69c0???????? c1e810 29c2 0fb7d2 d1ea }
		$sequence_8 = { 762a 0fb6c8 8d1489 8d0cd1 }
		$sequence_9 = { e8???????? 0f0b e8???????? 0f0b 90 90 90 }

	condition:
		7 of them and filesize <8011776
}
