rule MALPEDIA_Win_Wndtest_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "a60fab9e-f350-5d99-8e55-84b700dcda0e"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.wndtest"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.wndtest_auto.yar#L1-L117"
		license_url = "N/A"
		logic_hash = "c7d0b1dfe74b472c5174a4761a9428ccee3d781f889972cf04ca5a6d741a211f"
		score = 50
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8d1439 8a0410 320419 41 }
		$sequence_1 = { 56 ffd7 8b0d???????? a3???????? a1???????? }
		$sequence_2 = { 56 0fbe7001 83f60d 57 }
		$sequence_3 = { 880c3e 5f 5e 8be5 }
		$sequence_4 = { 75ea 8bcb 0fb6d2 c1e918 33ca c1e308 }
		$sequence_5 = { a3???????? a1???????? 50 51 e8???????? 83c408 50 }
		$sequence_6 = { 2bc2 40 50 e8???????? 8bd0 }
		$sequence_7 = { ffd7 8b15???????? a3???????? a1???????? 52 50 e8???????? }
		$sequence_8 = { 83c404 33c9 8d460a ba02000000 f7e2 }
		$sequence_9 = { 8b0d???????? 894808 e9???????? 8d46fe 8bff 668b4802 }

	condition:
		7 of them and filesize <901120
}
