rule MALPEDIA_Win_Magic_Rat_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "fef12775-f5d4-5648-9916-cb915f91f28b"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.magic_rat"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.magic_rat_auto.yar#L1-L111"
		license_url = "N/A"
		logic_hash = "d23de63f3611a6306ebe3970ddd7285c351120d5c12dbd45ba2d1d594ef068a3"
		score = 60
		quality = 45
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 85c0 7407 3dffff0000 756f }
		$sequence_1 = { f20f2ac9 f20f5cc1 f20f58c3 f20f2cc0 }
		$sequence_2 = { 0f84b8000000 83faff 7408 f0830001 }
		$sequence_3 = { 660f2ec2 7308 660f5705???????? 660f2ee2 f20f59c5 7308 660f5725???????? }
		$sequence_4 = { 29c2 89d0 c1f80e f7d8 eb08 }
		$sequence_5 = { 8b01 81e20080ffff 25ff7f0000 09d0 }
		$sequence_6 = { 8b4500 85c0 0f8472010000 83f8ff 740b f0836d0001 }
		$sequence_7 = { f20f58c3 f20f2cd0 01ca e9???????? }
		$sequence_8 = { 85d2 740b 83faff 74ad f0832801 }
		$sequence_9 = { 81fa???????? 7442 81fa???????? 744a }

	condition:
		7 of them and filesize <41843712
}
